### ISSUE TITLE
[Video Village Plugins] Filmbox Lite not installing, zip error macOS M1

### ISSUE THREAD

**Issue by kyeshmz** [videovillage/community#144]
My macOS is 13.1 (22C65)
It is a mac m1 pro.
Video Village plugins 1.4.4 

Trying to install filmbox lite returns zip error as below
<img width="524" alt="Screenshot 2023-05-05 at 9 36 21 AM" src="https://user-images.githubusercontent.com/12763472/236401679-f8f64e58-b92c-40de-81d5-e3996fc74fd2.png">

**Comment by gregcotten** [comment]
It's fixed!
