### ISSUE TITLE
Problem with installation

### ISSUE THREAD

**Issue by PaBu88** [videovillage/community#147]
Hello,
I have a problem with the installation of FIlmBox.
I have the license and I downloaded the video village plugins by the link that i received via mail.
After i lunch the installer and probably completed the installation, nothing happen. I can't see any window.
If i open the software via desktop icon or the exe in the folder nothing change.
I have Windows 10 Pro 22H2.

Thanks for the help

**Comment by gregcotten** [comment]
We're going to handle this directly via support email, thanks!

**Comment by alanmcseveney** [comment]
Same problem here.
