### ISSUE TITLE
Filmbox Lite in DVR

### ISSUE THREAD

**Issue by MacOSResolve18** [videovillage/community#151]
When dragging Filmbox Lite effect into a color page node, changes happen only in preview node, the viewer won't update. Same in edit page. In Fusion page the viewer will update but only for first clip of the timeline.
DVR 18 and 18.5
MacOS 12.6
MacBook M1 Pro.

**Comment by gregcotten** [comment]
Sounds like you're trying to use Filmbox Lite in a higher resolution than 2K. You should have received a warning message saying Filmbox Lite only works on 2K or lower timelines.

**Comment by MacOSResolve18** [comment]
Many thanks for your feedback. I was actually grading 2k footage on a 4k timeline. Now it works great.
