### ISSUE TITLE
New Filmbox update doesn't work backwards with compound node

### ISSUE THREAD

**Issue by Jacob2603** [videovillage/community#156]
Hi,

We have Filmbox stored in a Compound Node, and initially we started grading with the older version and then upgraded to the new version. 

If we now do a change to the grading and use CMD + Z to undo one action, the plugin has no selection of the version anymore and the screen turns magenta. If we open the Compound Node before we change anything it works as normal, but if we didn't open the Compound Node after the update it doesn't work. 

https://github.com/videovillage/community/assets/25831578/8845225e-2e31-49c3-95fc-d9790fb8e95e

**Comment by Jacob2603** [comment]
I just checked again on our side. I have stills from before the update. I compared them without opening the compound node and they look identical. After i make a change and press CMD + Z the picture is different and has less contrast due to the change to 2.0 instead of 1.0. Is there a way to downgrade to 1.8.1 in the meanwhile?


https://github.com/videovillage/community/assets/25831578/1269c4ce-0992-4a70-a7d2-86830f8498b1

**Comment by gregcotten** [comment]
Just to make it clear: 1.7.9 was the last version of Filmbox **before** we introduced Print Settings 2.0, so I'm assuming you wish to downgrade to that version?

I know this is a bit of a pain, but I think the best fix is to set your versions back to 1.0 (Legacy) manually instead of rolling back - it's possible that 1.8.1's "undo" bug caused the version settings to mess up.

**Comment by Jacob2603** [comment]
No I wish to upgrade to 1.8.1 because in this version it's visible to see if the version changes. Please send us 1.8.1 as a temporary fix.

I just tested it again with a project we last opened and graded 2 months ago ( this wasn't opened with 1.8.1 ) and the same problem occurs

To manually fix this we would've have to do it on 20+ projects and on thousands of shots this is a bigger issue.

**Comment by gregcotten** [comment]
I am truly confused! 1.8.1 and 1.8.2 shouldn't be different - are you saying that they are? Anyway, please email us at support@videovillage.com and we can get you setup to downgrade.

**Comment by Jacob2603** [comment]
Yes the bug is in both versions but we are already using features from the newer versions in some project thats why I only want to downgrade to 1.8.1 because there its visible if the version changes.
