### ISSUE TITLE
Filmbox upgrade error code 1 

### ISSUE THREAD

**Issue by LegalViking** [videovillage/community#170]
Hello,
Whenever I want to upgrade filmbox plugin it gives me error code:
An internal error code occured: Main.Helper.error (code 1)
How to fix that?
![filmbox_error](https://github.com/videovillage/community/assets/124371109/6bd1025d-26ab-4f1a-8f4d-cbf9db11fca1)

**Comment by gregcotten** [comment]
Not sure, you''ll need to email us your diagnostic logs to support@videovillage.com and we can help you from here.

Just open the Video Village Plugins app and click Help -> Export Diagnostic Logs and send us that zip. Thanks!

**Comment by makarii-kirillov** [comment]
Здравствуйте! Я скачал Filmbox Lite, но приложение Video Village вообще не открывается, просто никак не реагирует на нажатие. Стоит Windows 10. В Davinci плагин не отображается. Что это может быть?
