### ISSUE TITLE
CocoaLUT?

### ISSUE THREAD

**Issue by latenitefilms** [videovillage/community#172]
Hi Team,

I was just wondering why you removed the `CocoaLUT` project from your repo?

Obviously there's plenty of forks on GitHub, but just curious as to why you removed it, and if you're still maintaining it internally?

Thanks!

**Comment by gregcotten** [comment]
Wow, a blast from the past! CocoaLUT was a labor of love from around 10 years ago. No one else contributed to it except me and I didn't find open sourcing it to be at all useful. I think I removed it 2 or 3 years later when the first (and only) person to ask for a feature or bug fix ended up incorporating it into a paid FCP plugin without proper attribution.

Remnants of CocoaLUT remain in our codebase but we've mostly moved onto more performant pure Swift code. Hopefully that answers your question!

**Comment by gregcotten** [comment]
Correction: 11 years ago!

**Comment by latenitefilms** [comment]
Do you have any plans/interest in open sourcing (or licensing) your Swift implementation?

**Comment by gregcotten** [comment]
Not really, but feel free to reach out to us directly at support@videovillage.com
