### ISSUE TITLE
Scatter & Filmbox Version 2.2.3 install issue

### ISSUE THREAD

**Issue by fredsavoir** [videovillage/community#185]
Hi,
On brad new windows 10 64-bit with all the updates & AMD Threadripper Pro machine, the install always complain about:

Napoli.JS code Error 1.

So you can't install and use the software.

Could you please fix it ?

thanks

Fred

**Comment by gregcotten** [comment]
Hey Fred,

Please click Help->Export Diagnostic Logs and send those to support@videovillage.com
