### ISSUE TITLE
Scatter & Filmbox Version 2.2.3 install issue

### ISSUE THREAD

**Issue by fredsavoir** [videovillage/community#186]
Hi,
You are closing this issue but I did send the log and email to you support and got no reply from you.

IT's why I'm trying to get help from the community.

Fred

**Comment by fredsavoir** [comment]
So please let this issue open so some other customers & users could see the issue and exchange with me if they have some ideas why ?
Thanks

**Comment by gregcotten** [comment]
Support is mostly off on US weekends. The install issue you are having is related to an internal library and therefore not really fixable by anyone other than us! Should have a workaround available in a few hours in Video Village Plugins 1.6.1!
