### ISSUE TITLE
Cant install filmbox on macbook

### ISSUE THREAD

**Issue by LegalViking** [videovillage/community#194]
My client has bought the license for 3 months, ive downloaded plugin manager, registered license, and already 4th time installation has stopped in middle of progress without any explanation l.
How can i fix this, this is very urgent and quite inconvenient in front of the client

**Comment by gregcotten** [comment]
You need to email us at [support@videovillage.com](mailto:support@videovillage.com) with diagnostic logs. In the Video Village Plugins app, click Help -> Export Diagnostic Logs and email us.
