### ISSUE TITLE
Screen: Quick Look Plugin

### ISSUE THREAD

**Issue by apvlv** [videovillage/community#210]
### Discussed in https://github.com/orgs/videovillage/discussions/209

<div type='discussions-op-text'>

<sup>Originally posted by **apvlv** December  2, 2024</sup>
Hello,

i recently purchased Screen and one feature that is stated on the homepage is not working - the quick look plugin for the finder. Does anyone know how to activate it?

Thank you!</div>

**Comment by gregcotten** [comment]
Hi there. As far as I can tell the Quick Look plugin is working - what file type are you trying to Quick Look?

**Comment by apvlv** [comment]
Hi Greg,

thank you for your answer. For example .dpx is not working. I don't get a preview ik quick look. As the documentation is very thin on this product, which file types should work always. 

Thank you, 

Andrej

**Comment by gregcotten** [comment]
Also, can the DPX in question be opened by Screen?

**Comment by apvlv** [comment]
I'm using Sequoia 15.1.1 (24B91) on a macbook pro M2 14". The dpx is opening fine in the main app

**Comment by gregcotten** [comment]
OK I can reproduce this issue now... Working on a fix.

**Comment by apvlv** [comment]
Thank you Greg. Could you also specify which file formats should be possible to preview by Screen quick look plugin?

**Comment by gregcotten** [comment]
> Thank you Greg. Could you also specify which other file formats should be possible to preview by Screen quick look plugin? Is it only imaged based formats or also video like Canon Cinema RAW?

Just image formats that macOS natively doesn't support that Screen does. Unfortunately Quick Look Plugins are quite restricted by what they can do (strict memory limits, inability to load dynamic libraries, etc) and therefore we cannot add Quick Look support for most third party RAW formats.

I've fixed the issue in 1.7.17 - hopefully it works on your end!

**Comment by apvlv** [comment]
Yes, now it's working, thx!

and thanks for the clarification of the limitations of the os!
